
# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, host, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "vmd" "nvme" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/206d1ec2-c516-4ef2-8d71-13196af67328";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/4CB4-C547";
      fsType = "vfat";
    };

  fileSystems."/ubuntu" =
    { device = "/dev/disk/by-uuid/ff79eb2d-fe57-4eb7-b5ba-94dd89fe99c8";
      fsType = "ext4";
    };

  networking = {
    useDHCP = false;                        # Deprecated
    hostName = hostName;
    networkmanager = {
        enable = true;
        plugins = [ pkgs.networkmanager-openvpn pkgs.networkmanager_strongswan];
#        extraConfig =''
##           supersede domain-name-servers 127.0.0.53;
##            prepend domain-name-servers 208.67.222.222;
#          '';
        };
     interfaces = {
       lo = {
         useDHCP = true;                     # For versatility sake, manually edit IP on nm-applet.
         #ipv4.addresses = [ {
         #    address = "192.168.0.51";
         #    prefixLength = 24;
         #} ];
       };
       wlp0s20f3 = {
         useDHCP = true;
         #ipv4.addresses = [ {
         #  address = "192.168.0.51";
         #  prefixLength = 24;
         #} ];
       };
     };
 #    defaultGateway = "192.168.0.1";
 #    nameservers = [ "192.168.0.4" ];
     firewall = {
       enable = false;
       allowedUDPPorts = [ 500 4500 3389 5900];
       allowedTCPPorts = [ 500 4500 3389 5900];
     };
   };
   powerManagement.cpuFreqGovernor = lib.mkDefault "performance";
   hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

   services.resolved.enable = true;
   services.openvpn.servers = {
   };
}