global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'immich-server'
    metrics_path: /metrics
    static_configs:
      - targets: ['immich_server:2283']

  - job_name: 'immich-ml'
    metrics_path: /metrics
    static_configs:
      - targets: ['immich_machine_learning:8000']

  - job_name: 'node'
    static_configs:
      - targets: ['172.18.0.2:9100']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
