#
# Hardware settings for HP ProBook 650 G1 15.6" Laptop
# Dual boot active. Windows @ sda4 / NixOS @ sda5
#
# flake.nix
#  └─ ./hosts
#      └─ ./laptop
#          ├─ default.nix
#          └─ hardware-configuration.nix *
#
# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
#

{ config, lib, pkgs, modulesPath, host, ... }:

{
   imports =
      [ (modulesPath + "/installer/scan/not-detected.nix")
      ];

    boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "vmd" "nvme" "usbhid" "usb_storage" "sd_mod" ];
    boot.initrd.kernelModules = [ ];
    boot.kernelModules = [ "kvm-intel" ];
    boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/e88d78aa-b5cc-451e-9fd6-c1d07f28c884";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-af764af7-bb34-42d3-b374-de472c168a27".device = "/dev/disk/by-uuid/af764af7-bb34-42d3-b374-de472c168a27";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/1E60-6F1B";
      fsType = "vfat";
    };

  swapDevices = [  ];

  networking = with host; {
    useDHCP = false;                        # Deprecated
#    hostName = hostName;
    networkmanager.enable = true;
    interfaces = {
      enp0s31f6 = {
        useDHCP = true;                     # For versatility sake, manually edit IP on nm-applet.
        #ipv4.addresses = [ {
        #    address = "192.168.0.51";
        #    prefixLength = 24;
        #} ];
      };
      wlp0s20f3 = {
        useDHCP = true;
        #ipv4.addresses = [ {
        #  address = "192.168.0.51";
        #  prefixLength = 24;
        #} ];
      };
    };
#    defaultGateway = "192.168.0.1";
#    nameservers = [ "192.168.0.4" ];
    firewall = {
      enable = false;
      allowedUDPPorts = [ 500 4500 3389 5900 ];
      allowedTCPPorts = [ 500 4500 3389 5900 ];
    };
  };
  powerManagement.cpuFreqGovernor = lib.mkDefault "performance";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault
  config.hardware.enableRedistributableFirmware;

/*
    #POWERSAVE?? thinkfan
    boot.initrd.kernelModules = [ "coretemp" ];
    hardware.cpu.intel.updateMicrocode = true;
    hardware.enableAllFirmware = true;

    powerManagement.cpuFreqGovernor = "powersave";
    powerManagement.powertop.enable = true;

    # uncomment to lower CPU frequeuncy (0 - lowest, 100 - highest)
    # if it spins even on lowest frequency, then this can be hardware problem

    # system.activationScripts.cpu-frequency-set = {
    #     text = ''
    #         echo 75 > /sys/devices/system/cpu/intel_pstate/max_perf_pct
    #         # check freq with    "sudo cpupower frequency-info"
    #     '';
    #     deps = [];
    # };

    services.thermald.enable = true;
    environment.etc."sysconfig/lm_sensors".text = ''
      # Generated by sensors-detect on Tue Aug  7 10:54:09 2018
      # This file is sourced by /etc/init.d/lm_sensors and defines the modules to
      # be loaded/unloaded.
      #
      # The format of this file is a shell script that simply defines variables:
      # HWMON_MODULES for hardware monitoring driver modules, and optionally
      # BUS_MODULES for any required bus driver module (for example for I2C or SPI).

      HWMON_MODULES="coretemp"
    '';
    services.thinkfan.enable = true;*/
}
